# Generated by Django 5.1 on 2024-08-22 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_academicyear_end_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentteachercoursesemester',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentteachercoursesemester',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='studentteachercoursesemester',
            name='teacher',
        ),
        migrations.CreateModel(
            name='TeacherCourseSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.course')),
                ('semester', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.semester')),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.teacher')),
            ],
            options={
                'db_table': 'teacher_course_semester',
            },
        ),
        migrations.AddField(
            model_name='studentteachercoursesemester',
            name='teacher_course_semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.teachercoursesemester'),
        ),
    ]
