# Generated by Django 5.1 on 2024-08-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_studentteachercoursesemester_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentteachercoursesemester',
            name='ali',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
