# Generated by Django 5.1 on 2024-08-25 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_remove_studentteachercoursesemester_ali'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Feedback Category', max_length=100, unique=True)),
                ('code', models.CharField(default='Feedback Category Code', max_length=20, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feedback_category',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Role Code', max_length=100, unique=True)),
                ('name', models.CharField(default='Role Name', max_length=100, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(default='BUILDING001', max_length=100),
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='university.course')),
                ('prerequisite_course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='university.course')),
            ],
            options={
                'db_table': 'course_prerequisite',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='Comment', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('teacher_course_semester', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.teachercoursesemester')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.user')),
                ('feedback_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.feedbackcategory')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.role')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.user')),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
    ]
