# Generated by Django 5.1 on 2024-08-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_feedbackcategory_role_department_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='COURSE100', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='feedbackcategory',
            name='code',
            field=models.CharField(default='Feedback Category Code', max_length=100, unique=True),
        ),
    ]
