# Generated by Django 5.1 on 2024-08-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_student_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated',
        ),
    ]
